layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: lochan.melam
  # hackerrank: your_username
  instagram: lochan_melam28
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Competative Programming
    web_url: https://www.geeksforgeeks.org/how-to-begin-with-competitive-programming/
    image_url: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAFgAqAMBIgACEQEDEQH/xAAbAAACAgMBAAAAAAAAAAAAAAAAAQUGAgMEB//EADcQAAIBAwMDAwMDAgMJAQAAAAECAwAEEQUSIQYTMUFRYRQiMnGBkRVCFmLRByMkNDWhscHwM//EABkBAQEBAQEBAAAAAAAAAAAAAAABAgMEBf/EAB8RAQACAgIDAQEAAAAAAAAAAAABAhESAyEEIkExMv/aAAwDAQACEQMRAD8A8jp0227jszt9Nx5rfp9qb2+htg2wSNy2M7QBknHqcA4Hqa9iuaipm8sbI6dNcWRnjMJXek0gfepYKDwowckcc+v7w1AUZ58iuiytze30NuhCmWQLkD8RnzV+bR9PtrQRR2sRHAYsoLN8k1w5vIrxTET9evxvDv5ETMTiIec0VL65p9ta3Ja3mUIwz2/O0+oFRFdaXi8Zh5r10tNZ+CiisnKs5KrtB8LnOK0yxp+mcj9KVOgVFFFAUwCTgUqKAooooCissMq5wQrZGcecYz/6rGgKKf7ClQP1OPHpXXb20sQiupJ0tFOGidsl29mVV58+CcD5rDT4kmvI1lG6JMySj3RQWYfuBj960zTSXErzTtukc7mPz/p8UR7Bpmm20kMX0dnps0FxZIl4LxVV5JZI9y4IJCgnGACuCH8nAryTUBbLfTrYrOtsJCI1uCDIo9mI4yPFdGlapc6al1HbsgW5VQxcZ2MjBkcezKc4Pya5Lq4lu7ma5uG3zTOZJGx+TE5J/msxE5GdtdyWrK8IUMrBg3rkVahrulXFsGnknEvG6OXc2P0xwaqEPaM8QuXdIN691kGWVM/cQPfGatV50paOkyaXcXQuoe0THeABX3wPNtUqvnanrgcH4rny8dL/ANO/Dz24c4jOUFrOoDULlWjTZDGNsa/+T/8Ae1R9WJulpbXWDY306SbbaWciyO937eQY1BH5ZU+njn4ranSM16UfTzLBHJtCx36kSAkIWOUXAAEi4zgtzgVuutYxDne83tNpViirO/Rl0qljf2mxYzIzBJjgBQ3jZknBPHx6UXPRt5FFLJ3rePsRN3e9JgNIrzAhMDJG2Ennnn+LtDKsn9c0qsGt9LXGj28lzJdQXEMcxj2xkrI6hym4KRxyrDH6ealNX6E7M0g029Uxxqd31bY+7c6gAhQMnY2RjjA5ORTaBTFO1g2AcHOCMiirdedCzrdCO0vYO20qQp3ywdmJVC20LkDewHwOfk6U6Ku3WJxqFj25I+4GzJkKQCCV25GQc8jjwabQir/oKbbeNoI45yc5NWaLonUGlMTXVpHIqb5A4kCqCQB9xTaTll4ByOfauXTOmLjUbdpIrqBHS4kgdGSRsFTGAcqpzlpVHA4HNNoVBAEnA80qzmiaGaSGTG+NyjYORkHB59axwcZ9M4z81oKtypbm1kked1uFkUJEI8qynOTuzxjjjHr/ABqAyQOOfenIhjdkJUlSQSrZBx7EeaBKcEHAOOcHkGiilRMOl7vNuYYYIYFb/wDTt7j3OQQCWJOBjOM4z6ZFaoREZAJ2dY8HlACc448/OK108nbt4xnPgZ/milRTpUARkHI4rcb+5LMTezk/3Zmb0GOefYkfoan/APZ/plprPU0EGoQrLa20EtzJCvBn2AsF/ckfsMV36P17eyanB9ZounX1lkmLToLCNTFwdvaKrkEfOcjNZmfiKg1xO8qzPPK0qY2SM5LLjxg+Rin9TcZci4my7B3PcOWYchj7ke/mrHY9M6amn2Fxr2svp82pgtaRR2plCJuKh5DkYBOcAegro/wfYWWn6nPrurzWk2l3otrqOG17obdnaUO4ZJAzzjFTaBXLTV9Rs2ka3vZlaSMxsWO44PnGc7T/AJhgj3rnN1clDGbmfYV2le4cFfbHt8VbdX6LsbFNbgttbe41DS7cXbRG0KRmI7cAtn88ODwMelZXPSnTlsdM73U1wg1SBZLb/gMlNxIBkw3C5GOOfNNqinvcTuoV7iZlDbwGkYjd43efOOM1kby7bcWu7g7wQ2Zm+4HGc885wP4FW+y/2e3ipdy6sNQCQXb2iJpli107sv5OccKnIxnk88cVvj6NsNKt+po9duJvqLK1hmtZUt2/CRhtfYSCGJ+0qfx5pvVVJW+u9zFby53btxImbO4DGTz5xxS+ruQNgup8AHjutwCcn19T5969A07QNLvOounbXUL2S6sJtIaa3C2ixFgvcIV9pycbSck84APmo210nSbjp7Tt2uTrps2rSQGQ6egdJNn2sTuyVK7cjOBk+1NoRUheXQdXF1cBl3bWEzZXd+WOeM+vvWVm83cEcV2bYHc24ylFztPt6nx++KuTdBWxa7t49TuRerqh021jltQFmk2hsk7uFAySfbHvWnWOgpLPTL+7tH1N205d9x9ZpklvHKoOC0Tnzjzg8kcjxTeopQ4AwMD2rpF9cjT2sBKfpWlEpjwPzAxmuamRgD5+a3MKVFFFAySfJzRUno2gahrkpTTIC6pgPJIQqIceCf8ATn4p1nev5lmb1j9lH29vNdSdu3jZ2AyceFHuSeAPk8VaZukrGHo2TWTqm67QBhGuO0+WxtXIyTjnPj9uaq8Vw8S7PziLB2hYnY5HjcM81v1K77/biWQyIn3tIQR3ZGA3Nj24Cj2C/NWcq4qKKYI9Rniqrr0jU7vRtTt9R0+XtXNu+5GxkeMEEeoIJB/Wp/8Axjb2sst5ovTmn6ZqcqspvI5Xk7W4EMYkb7YyQTyPeojpmzs9R6gsLDUfqBb3c6QbrcqHVnYKp5BGMkZqw3nSNjfQaiemv6j9Rp98to8d+8QS4JLjMb/aMgpkg+hrFprntEfp3VUcNhY2uqaJaaq+nE/RTTyujRgndtYLxIoPIBpXHVrXmjatZX+mQ3Fzqk/1E94Z3UiQZ2kIOMLnAHr61rPRPUq3C276S6ysruVaaIbFUgEsd2EHIwWxn0zWJ6V1T6tdLWxuv6uA0skDCMRCDA2yCXdtIyTznHzmnqO+frdJtS1C+l0O3YX9gLO6iFzIBIBtwwPocIowKmNc1TTNJ03pvfa6HrdxYWaRI8N+zNDKpLHcqHDp+JGfXNV3/AvU+YB/S/8AmGKw/wDFQYlP+X7+R8jitQ6N6h7xibTgjhFdu5dQoEDHChiXAVif7Tg/FTFRtHVTXsU8HUem2+sRSXT3adyV4Xhkf8trLztOB9vwKwtupooZNWX+i2K2mo26wNaQM0SR7CCjAjknIyc+a123SPUFy14sOmuWspe1cq00aGJuPIZhxz+Xj5p3/R/UOnWtxdXumNFDbLvlbvRsQvH3ABiWXkfcAR81fUSA62WO/wBEu7bQ7eE6VA1sqfUyMJYmVgVOfH5Mc+eaj73X7S46aOhQaHDbxfVG5jmF1I7Ix4xg8H7Pt/7+a3noPqkD/pDMSncUJcQsXX3UB8sPfGcetKz6S1RdXSyv9OnbNrJdbLa5g3OgUgMrFipw2MgEnAPFPUZ6r1tqmo3Oi3QEcFzpKDZKnJll+0GRhjyQigj2FadQ1vS7y1vex03p9ne3WDJcBnl5LAntqxxF68jPtStOi+pLy0t7q20zuQ3MfchdbiECQYzgAvnOP7fPxWjSumNb1ezW807T3mt3cpGxkRDIw8hAzAvj/KDTFREUDHrXZqul3uj3j2mpQiG4Q4ZO4j7TjOCVJHrXFW1NQWYKPJIAyQB/J8Vix2oW9hmnRQe79PaZBpmi2UCEBFiVmZf7mYZY/ueadVfovrWxfSotM1idbe4t0EcU0hwkqjxz6EDA580V8nyOKeK/pSJz28OLTM7ZeX06VFfWe46VFFBKdMXVnY9Q6de6jJMltaXEdw3Zi3sxRgwXBI84xn0+altc6kGtdRRtfatqM2jR3ZuIhJEC8Y8gCPdgkfjnPjJ9cVVaKmsZyLvqHUOhX2qdSRSy6h/TtdMUzXAt17tvJG7Mq7N2HTB55B4HHFdWnazZalE/S+n2mqXGnHSzbLcxQh7rKyGUv2weUycbAc4/ivPqyR3jdXjdkdTlWUkEH4IrOkI9G1MaV08/QqXr6jDFpjzXbJJbKJ2/3yOuY93+7DFWwCSQPeoWw1fQrW+1mQPKzXc6zQ3k+mRTuUJYyRGN2wu4sPuyfx9KqcjvI7SSO0kjcszsSSfkmnI0bbe3GUAUBstu3HHJ+M+1IpGOxeta6g6b1BuqpY7nUkfW44tiGyTETRkEAnucgkYrVP1HoVxeX0rzXyJfaFHp7kWykxSoIxwN/wBynYeePNUenV0gXtte6aW8tmW61MwroL6PIxslBGUKiQDuc/kePjzS0fqTQIJOnJ7ua/STSbG4tpI47RXDmQOAQd49JM+PTHrkUSnU0gXbTNe0DSx0mYrjUJjotzM8260VN6yckr955BAGPXJ8Y5kdHs7TqGPQWittdkj0i6aCCa3sx27he53AWbfiFhu+4nIx458UPS786dPJKLW2uN8LxbbiPeBuBGR88/xXOk80aukc0iJJ+ao5UN+oHmpp2qQ6rljn6r1uaFleOTUblkdTkMDK2CKjQuVY5H2+5Gf2HrSGAMYHx8Uq6R0HQKKVAUUxj1GeKKBUUUUBRRRQFFFFAUUUUBRRRQFFFFAUUUUBRRRQFFFFAUUUUBRRRQf/2Q==
    
  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png

theme: jekyll-theme-slate
